platform: ILLUMINA

exp: exp2_MHC

parent_dir: /home/tuba/herpov/tcr-pmhc-sc-project

raw_file:
  MHC : MHC-2_S1_L001_R1_001.fastq.gz
  CD8 : CD8-2_S2_L001_R1_001.fastq.gz
  EXTZ : -2_S1_L001_R1_001.fastq.gz
  EXT : -2_S1_L001_R1_001.fastq

