exp: exp13
run: run2
msg: "1OS barcode system for pMHC and commercial barcodes for hashing."
srt:
  - positive
  - negative
#parent_dir: /home/tuba/herpov/tcr-pmhc-sc-project

demultiplexed: True #Is data demultiplexed or not?
index : SI-TT-A1 #exp2:SI-GA-A2/SI-GA-E6, exp3:SI-GA-A2 #exp6:SI-GA-A4 #exp7: SI-GA-A5 #netTCR1: SI-TT-A3 #netTCR2: SI-TT-A4 #exp9:SI-TT-A2 #exp10:SI-TT-A1

############################################################################
#                                  Run ID                                  #
############################################################################
platform: IONTORRENT
mapping: KMA
mapping_args: -1t1
barcode_system: AKB #COM

############################################################################
#                                  BRC mapping                             #
############################################################################
brc_info: /home/tuba/herpov/tcr-pmhc-sc-project/tools/barcode_oligos/all_oligos.csv
oligo_a:
  15mer: /home/tuba/herpov/tcr-pmhc-sc-project/tools/barcode_oligos/oligo.15mer.rv.fa
  25mer: /home/tuba/herpov/tcr-pmhc-sc-project/tools/barcode_oligos/oligo_a.25mer.fw.fa
oligo_b:
  15mer: /home/tuba/herpov/tcr-pmhc-sc-project/tools/barcode_oligos/oligo.15mer.rv.fa
  25mer: /home/tuba/herpov/tcr-pmhc-sc-project/tools/barcode_oligos/oligo_b.25mer.fw.fa
samples:
  default: /home/tuba/herpov/tcr-pmhc-sc-project/tools/barcode_oligos/samples.fw.fa

commercial_brc: /home/tuba/herpov/tcr-pmhc-sc-project/tools/barcode_oligos/totalseq-c.xlsx

dummy_ext: 
  R1: S1_L001_R1_001.fastq.gz
  R2: S1_L001_R2_001.fastq.gz
raw_file:
  EXTZ : S1_L001_R1_001.fastq.gz
  EXT : S1_L001_R1_001.fastq

############################################################################
#                                   BRC tools                              #
############################################################################
cutadapt: /opt/anaconda3/bin/cutadapt
KMA: /home/tuba-nobackup/shared/src/kma/kma
mapping_args: -1t1
pairwise_aligner: /home/tuba-nobackup/shared/EMBOSS/bin/water

############################################################################
#                                Cellranger                                #
############################################################################
longranger: /home/people/marquard/tuba/tcr_seq/10x/apps/longranger-2.2.2/longranger
cellranger: /home/tuba-nobackup/shared/cellranger/cellranger-6.1.1/cellranger
vdj_ref: /home/tuba-nobackup/shared/cellranger/reference/refdata-cellranger-vdj-GRCh38-alts-ensembl-5.0.0 #/services/tools/cellranger/refdata/refdata-cellranger-vdj-GRCh38-alts-ensembl-5.0.0
gex_ref: /home/tuba-nobackup/shared/cellranger/reference/refdata-gex-GRCh38-2020-A/ #/services/tools/cellranger/refdata/refdata-gex-GRCh38_and_mm10-2020-A

############################################################################
#                                 Similarity                               #
############################################################################
s2s: /home/tuba/herpov/tcr-pmhc-sc-project/tools/seq2score_db_kernel
blf: /home/tuba/herpov/tcr-pmhc-sc-project/tools/BLOSUM50
qij: /home/tuba/herpov/tcr-pmhc-sc-project/tools/blosum62.qij

############################################################################
#                                 Plotting                                 #
############################################################################
thrs_vals:
  - opt
  - exp9.2
  - 10ucm
  - 10ucm5dum
  - 20ucm
  - 20ucm5dum
  - 30ucm
  - 30ucm5dum

plot_type:
  - peptide_per_clonotype_by_gem_size
  - peptides_per_gem
  - multiple_peptides_per_gem_w_filtering
  - mhc_read_count_per_clonotype
  #- tcr_read_count_per_clonotype

umi_delta:
  - umi_delta0
  - umi_delta1
  - umi_delta2

filtration:
  - no_filtration
  - exclude_single-chain_TCRs
  - exclude_ambiguous_and_single-chain_TCRs

version: 1

bc_thresh:
  - b1
  - b5
  - b10

tcr_thresh:
  - t1
  - t5
  - t10

ecs_bool:
  - False

ess_bool:
  - False

#https://stackoverflow.com/questions/64271392/overwrite-nested-config-options-on-command-line

